/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.page;

import java.awt.Color;
import javax.swing.JComponent;
import views.event.EventMenuSelected;
import views.form.Form_Account;
import views.form.Form_Class;
import views.form.Form_Course;
import views.form.Form_Enroll;
import views.form.Form_Home;
import views.form.Form_Mark;
import views.form.Form_Role;
import views.form.Form_Student;
import views.form.Form_Subject;
import views.form.Form_Teacher;

/**
 *
 * @author vieta
 */
public class Main extends javax.swing.JFrame {

    private Form_Home home;
    private Form_Account form_account;
    private Form_Role form_role;
    private Form_Class form_class;
    private Form_Course form_course;
    private Form_Mark form_mark;
    private Form_Student form_student;
    private Form_Teacher form_teacher;
    private Form_Subject form_subject;
    private Form_Enroll form_enroll;

    public Main() {
        initComponents();
        home = new Form_Home();
        form_account = new Form_Account();
        form_role = new Form_Role();
        form_class = new Form_Class();
        form_course = new Form_Course();
        form_mark = new Form_Mark();
        form_student = new Form_Student();
        form_teacher = new Form_Teacher();
        form_subject = new Form_Subject();
        form_enroll = new Form_Enroll();
        
        menu2.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
                switch (index) {
                    case 1:
                        setForm(home);
                        break;
                    case 2:
                        setForm(form_account);
                        break;
                    case 3:
                        setForm(form_role);
                        break;
                    case 4:
                        setForm(form_student);

                        break;
                    case 5:
                        setForm(form_teacher);
                        break;
                    case 6:
                        setForm(form_mark);
                        break;
                    case 7:
                        setForm(form_course);
                        break;
                    case 8:
                        setForm(form_subject);
                        break;
                    case 9:
                        setForm(form_class);
                        break;
                    case 10:
                        setForm(form_enroll);
                        break;
                    default:

                }
            }
        });

        //  set when system open start with home form
        setForm(new Form_Home());
    }

    private void setForm(JComponent com) {
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new views.swing.PanelBorder();
        mainPanel = new javax.swing.JPanel();
        menu2 = new views.component.Menu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên");
        setFocusCycleRoot(false);

        panelBorder1.setAlignmentX(0.0F);
        panelBorder1.setAlignmentY(0.0F);

        mainPanel.setBackground(new java.awt.Color(247, 247, 247));
        mainPanel.setPreferredSize(new java.awt.Dimension(1000, 0));
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu2.setMinimumSize(new java.awt.Dimension(230, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelBorder1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private views.component.Menu menu2;
    private views.swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
